Avoid a  `ModuleNotFoundError` in `streamlit`
Running a `streamlit run ../analysis/backtester_ui.py`
causes a `ModuleNotFoundError` :
```
File "/LiuAlgoTrader/.venv/lib/python3.10/site-packages/streamlit-1.15.1-py3.10.egg/streamlit/runtime/scriptrunner/script_runner.py", line 564, in _run_script
    exec(code, module.__dict__)
  File "/LiuAlgoTrader/analysis/backtester_ui.py", line 15, in <module>
    from streamlit.uploaded_file_manager import UploadedFile
ModuleNotFoundError: No module named 'streamlit.uploaded_file_manager'
```

The location of `UploadedFile` was changed from `streamlit.uploaded_file_manager` to `streamlit.runtime.uploaded_file_manager`.